### ISSUE TITLE
Sorting will disrupt items with certain containers

### ISSUE THREAD

**Issue by Surgeol** [Origins-Tech/InventiveInventory#10]
**Mod Version & Minecraft Version**  
Minecraft version: 1.21
Mod Version: 1.1.1
Mod List: 
- Inventive Inventory 1.1.1
- Fabric API 0.102.0+1.21
- Mod Menu 11.0.2

**Describe**  
Currently, when the mouse is over the UI of some containers, pressing "R" disrupts the arrangement of items within it. This bug appears in survival mode,.

**Expected behavior**  
I assume that players will always be able to sort their inventory. But should disable the sorting feature when player's mouse is hovering these containers UI, such as furnace, brewing stand, blast furnace, smithing table, craft table, etc.

**Screenshots**  

https://github.com/user-attachments/assets/74f87b90-6a09-4345-a6e8-47cd283c5fcc

**Comment by Disturbtion273** [comment]
Hey there,
thank you for your report.

We could replicate the issue and fixed it locally. 
This bug fix will be part of the next update.

Thank you very much
Your Inventive Inventory Team
