### ISSUE TITLE
Sorting in a container does not work

### ISSUE THREAD

**Issue by Drakon1505** [Origins-Tech/InventiveInventory#26]
**Mod Version:1.1.2 & Minecraft Version:1.21.1**  
Doesn't work in both single player and server.

**Describe the bug**  
By default, sorting is assigned to the letter R. I press it, but for some reason it only works with the inventory?

**To Reproduce**  
1. Go to the "corresponding version of the game and mod"

2. Hover over the container 
2. Click on the "letter R"
4. View the error

**Expected Behavior**
I expected the container to be sorted

**Screenshots**
This doesn't make sense

**Additional Context**
Add any other context about the issue here.

**Comment by Disturbtion273** [comment]
Thank you for your report.
The bug is now fixed and the new version should be online now on Modrinth and Curseforge.

Your Inventive Inventory Team
