### ISSUE TITLE
1.1.3 for 1.20.4 requires Java 21 

### ISSUE THREAD

**Issue by Alasofia** [Origins-Tech/InventiveInventory#31]
**Mod Version & Minecraft Version**  
Mod version 1.1.3
MC Version 1.20.4
Java 17 (as required by 1.20.4)

**Describe the bug**  
The mod will not start unless I ignore Java compatibility checks and launch Minecraft with Java 21. This is unsafe and only works in some launchers.
The log clearly says "Inventive Inventory requires JAVA 21, not JAVA 17".

**To Reproduce**  
1. Add Inventive Inventory and prerequisite mods to your game.
2. Launch.
3. Fail to launch.

I expect I can also bypass this by modifying the fabric.mod.json file, but that really should be left in place at compilation.
Thanks!

**Comment by Disturbtion273** [comment]
Thank you very much for your report.
We are so sorry that we missed that and have fixed that immediatley.
The new version should be uploaded!
