### ISSUE TITLE
Move Items

### ISSUE THREAD

**Issue by Cam42exe** [Origins-Tech/InventiveInventory#46]
**Mod Version & Minecraft Version**
I am using 1.21.3 and the newest mod-version.

**Describe the feature**
I want to be able to press and hold a key (configuarable) to move all stacks of one item into the other inventory.

**Screenshots**
If applicable, add screenshots to help explain your feature.

**Additional context**
For example, I am at a chest with 9 stacks of dirt, and I want to move all the dirt into my inventory. I want to just press a key and do a normal mouse click and everything moves the inventory.

**Comment by Disturbtion273** [comment]
Hi there,
Actually this feature is already included in Minecraft out of the box. You need the item you wanna move in your hand and then shift+double click on other stacks with the same item. 
We are aware it is not as convenient but we don't want to invest time into something that is already perfectly working and doesn't add anything new into the game. It just like bloats our mod with load of stuff. The name "Inventive" stands for new, innovative features, not for rethinking existing ones.

Thanks for the idea though!
