### ISSUE TITLE
Changing settings in game get reset

### ISSUE THREAD

**Issue by iainvm** [Origins-Tech/InventiveInventory#5]
**Mod Version & Minecraft Version**
I'm using the latest code from the git repo

**Describe the bug**
The mods settings keep resetting when I relaunch the Minecraft client

**To Reproduce**
- launch Minecraft
- change settings in ModMenu
- relaunch
- check settings

**Expected behavior**
Settings to be the same as before

**Comment by LU-XD** [comment]
Hey iainvm,
thank you a lot for your report.

We were able to reproduce the issue and we will fix it in the next few days.

Your Inventive Inventory Team

**Comment by LU-XD** [comment]
Hey again,

the bug should be fixed now and the new code is pushed to the repo.
If you find any other bugs please let us know.

Your Inventive Inventory Team

**Comment by ZTenski** [comment]
I built this locally for 1.21.1 and fabric 103, works perfectly now and maintains the settings just fine. Thank you.

**Comment by Disturbtion273** [comment]
Hey there,
we have enrolled a new version of our mod. Settings will be saved in this version and you can now download it easily again via Modrinth or Curseforge with the convenience of getting updates and everything these launchers have to offer.
So just remove the jar file from your mods folder and install it from your launcher.

Thanks for using our mod
Your Inventive Inventory Team
