### ISSUE TITLE
Inventory Slot Lock

### ISSUE THREAD

**Issue by Cramram** [Origins-Tech/InventiveInventory#7]
I would love if it there were a menu to customize the color of the outline that used to appear when locking slots. I do like the Lock icon that's in the latest version, but I wish it was more customizable. Personally, I'd love the option to just have a darker inventory slot for when an item is locked, essentially just the option to remove the lock icon.

**Comment by Strobel273** [comment]
Hey Cramram,
thanks for the idea.

Yeah, we can totally do that.
Just for clarity: In the new versions there are no more outlines, only color fills. Do you just want to customize the colors or do you want the outlines back (customizable of course) AND be able to change colors?

Your Inventive Inventory Team

**Comment by Cramram** [comment]
I would love the ability to have both, that would be awesome. I just think both the bright red outline and the lock icon are a little intrusive personally.
