### ISSUE TITLE
An earlier version of fabric cannot be started

### ISSUE THREAD

**Issue by LuoliiQaQ** [Origins-Tech/InventiveInventory#8]
Hello, can you adapt to 0.100.7 and lower versions of the fabric api? This module can only run on the higher version of the fabric api, and the lower version cannot be started. The reason may be a little complicated, but I hope you can  the 0.100.7 and other lower versions of the fabric api?

**Comment by Strobel273** [comment]
Hey,
this isn't a problem at all. But before releasing a new version we want to do a few other things as well, so if you want it now, we could send you the jar file via Discord.

Best regards

**Comment by Disturbtion273** [comment]
Hey there,
we have enrolled a new version of our mod. It comes directly with support for older fabric versions and you can now download it easily again via Modrinth or Curseforge with the convenience of getting updates and everything these launchers have to offer.
So just remove the jar file from your mods folder and install it from your launcher.

Thanks for using our mod
Your Inventive Inventory Team
